### ISSUE TITLE
无法资源转换

### ISSUE THREAD

**Issue by apples1949** [twinstar6980/Twinning.Documentation#4]
数据包发布地址：https://tieba.baidu.com/p/9059797861 
下载地址：https://www.123pan.com/s/Rz8VVv-kN38v.html 提取码:lite（11.5）
工具使用版本：66_42_112_46_37.windows.x86_64
![c6f05e7a9c9288843b9c46af3ff56810](https://github.com/twinstar6980/Twinning.Documentation/assets/49244656/a15e266b-8453-4228-af74-28f22fe9c97e)
[PROPERTIES.zip](https://github.com/user-attachments/files/16076280/PROPERTIES.zip)

**Comment by apples1949** [comment]
数据包发布地址：https://tieba.baidu.com/p/9056741916
下载地址：https://www.123pan.com/s/c5vzVv-T3hl3.html 提取码：0hzC
![dd27a7f8321b2ef2d296cc0f65d77d26](https://github.com/twinstar6980/Twinning.Documentation/assets/49244656/b73644ce-045e-445b-bd34-1881ba735518)

**Comment by twinstar6980** [comment]
打开 `script/Support/PvZ2/ResourceConvert.js` ，定位到 `find_item_by_path_ignore_case` 函数，在其中的 for 循环体开头添加以下代码：
```js
if (item.additional.type === 'dummy') {
  continue;
}
```
修改后重新运行应用，看看能否完成转换。

**Comment by apples1949** [comment]
> 打开 `script/Support/PvZ2/ResourceConvert.js` ，定位到 `find_item_by_path_ignore_case` 函数，在其中的 for 循环体开头添加以下代码：
> 
> ```js
> if (item.additional.type === 'dummy') {
>   continue;
> }
> ```
> 
> 修改后重新运行应用，看看能否完成转换。

不会再弹错误了。目前正在解图中。大体上应该没问题了

**Comment by apples1949** [comment]
![39EF1E7C3DF5722C4A063E39D9B34590](https://github.com/twinstar6980/Twinning.Documentation/assets/49244656/c52a916e-022a-472e-ab28-05bc1cb9fe7b)
确认无误
